#!/bin/sh

[ -n "${DEBUG}" ] && set -x
set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

case "$1" in
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	purge)
		if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
			. /usr/share/dbconfig-common/dpkg/postrm
			db_purge
		fi
		if which ucf >/dev/null 2>&1; then
			ucf --debconf-ok --purge /etc/tracks/database.yml
			ucf --debconf-ok --purge /etc/tracks/site.yml
		fi
		# package-generated or runtime files are removed
		rm -f /usr/share/tracks/db/schema.db
		rm -rf /var/run/tracks
		rm -rf /var/log/tracks
		rm -rf /usr/share/tracks/tmp
		rm -rf /var/lib/tracks/*/sessions
		rm -rf /var/cache/tracks
		rm -rf /etc/tracks
    rm -rf /usr/share/tracks/vendor
	;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
